"""Stable exception and error-code vocabulary for CERA."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INTAKE_INVALID = "CERA_INTAKE_INVALID"
    EVIDENCE_SERVICE_UNAVAILABLE = "CERA_EVIDENCE_SERVICE_UNAVAILABLE"
    REASONER_UNAVAILABLE = "CERA_REASONER_UNAVAILABLE"
    REASONER_CONTRACT_INVALID = "CERA_REASONER_CONTRACT_INVALID"
    COMPOSER_UNAVAILABLE = "CERA_COMPOSER_UNAVAILABLE"
    COMPOSER_CONTRACT_INVALID = "CERA_COMPOSER_CONTRACT_INVALID"
    INTERNAL_CONTRACT_INVARIANT_FAILED = "CERA_INTERNAL_CONTRACT_INVARIANT_FAILED"
    ADULT_AUTHORITY_UNRESOLVED = "CERA_ADULT_AUTHORITY_UNRESOLVED"
    ADULT_PLANNER_UNAVAILABLE = "CERA_ADULT_PLANNER_UNAVAILABLE"
    ADULT_CONTEXT_INVALID = "CERA_ADULT_CONTEXT_INVALID"
    ADULT_CRAFT_CATALOG_INVALID = "CERA_ADULT_CRAFT_CATALOG_INVALID"
    ADULT_CRAFT_SELECTION_INCOMPLETE = "CERA_ADULT_CRAFT_SELECTION_INCOMPLETE"
    ADULT_SPECIFICITY_FAILED = "CERA_ADULT_SPECIFICITY_FAILED"
    ADULT_SEMANTIC_SPECIFICITY_FAILED = "CERA_ADULT_SEMANTIC_SPECIFICITY_FAILED"
    ADULT_BEAT_REPAIR_FAILED = "CERA_ADULT_BEAT_REPAIR_FAILED"
    ADULT_ROUTE_SYNC_FAILED = "CERA_ADULT_ROUTE_SYNC_FAILED"
    ADULT_MECHANICS_CONTRACT_INVALID = "CERA_ADULT_MECHANICS_CONTRACT_INVALID"
    BLOCKED_NONCONSENSUAL_EVENT = "CERA_BLOCKED_NONCONSENSUAL_EVENT"
    RECEIPT_MISSING = "CERA_RECEIPT_MISSING"
    RECEIPT_MALFORMED = "CERA_RECEIPT_MALFORMED"
    RECEIPT_INTEGRITY_FAILED = "CERA_RECEIPT_INTEGRITY_FAILED"
    RECEIPT_STALE = "CERA_RECEIPT_STALE"
    RECEIPT_WRONG_BRANCH = "CERA_RECEIPT_WRONG_BRANCH"
    RECEIPT_DUPLICATE_CONFLICT = "CERA_RECEIPT_DUPLICATE_CONFLICT"
    EVIDENCE_INSUFFICIENT = "CERA_EVIDENCE_INSUFFICIENT"
    STATE_CONFLICT = "CERA_STATE_CONFLICT"
    TRANSACTION_ROLLED_BACK = "CERA_TRANSACTION_ROLLED_BACK"
    VERIFIER_FAILED = "CERA_VERIFIER_FAILED"
    CREATOR_REVIEW_FAILED = "CERA_CREATOR_REVIEW_FAILED"
    DELIVERY_AFTER_COMMIT_FAILED = "CERA_DELIVERY_AFTER_COMMIT_FAILED"
    RENDER_FAILED = "CERA_RENDER_FAILED"
    CREATOR_GENESIS_PACKAGE_UNAVAILABLE = "CERA_CREATOR_GENESIS_PACKAGE_UNAVAILABLE"
    CREATOR_AUTHORITY_UNAPPROVED = "CERA_CREATOR_AUTHORITY_UNAPPROVED"
    SYNTHETIC_GENESIS_REJECTED = "CERA_SYNTHETIC_GENESIS_REJECTED"
    GENESIS_SOURCE_AMBIGUOUS = "CERA_GENESIS_SOURCE_AMBIGUOUS"
    EVIDENCE_SNAPSHOT_STALE = "CERA_EVIDENCE_SNAPSHOT_STALE"
    EVIDENCE_ACCESS_DENIED = "CERA_EVIDENCE_ACCESS_DENIED"
    EVIDENCE_LIMIT_EXCEEDED = "CERA_EVIDENCE_LIMIT_EXCEEDED"
    EVIDENCE_INDEX_INVALID = "CERA_EVIDENCE_INDEX_INVALID"
    EVIDENCE_BRIDGE_UNAVAILABLE = "CERA_EVIDENCE_BRIDGE_UNAVAILABLE"
    EVIDENCE_BRIDGE_CONTRACT_INVALID = "CERA_EVIDENCE_BRIDGE_CONTRACT_INVALID"
    CONSOLIDATOR_UNAVAILABLE = "CERA_CONSOLIDATOR_UNAVAILABLE"
    CONSOLIDATION_CONTRACT_INVALID = "CERA_CONSOLIDATION_CONTRACT_INVALID"
    DERIVED_VIEW_STALE = "CERA_DERIVED_VIEW_STALE"
    POST_PUBLICATION_WORK_FAILED = "CERA_POST_PUBLICATION_WORK_FAILED"
    POST_PUBLICATION_WORK_INTERRUPTED = "CERA_POST_PUBLICATION_WORK_INTERRUPTED"
    POST_PUBLICATION_RETRY_NOT_AUTHORIZED = "CERA_POST_PUBLICATION_RETRY_NOT_AUTHORIZED"
    EVALUATION_CONTRACT_INVALID = "CERA_EVALUATION_CONTRACT_INVALID"
    EVALUATION_CONTAMINATED = "CERA_EVALUATION_CONTAMINATED"
    PROVIDER_CONFIG_INVALID = "CERA_PROVIDER_CONFIG_INVALID"
    PROVIDER_BUDGET_EXCEEDED = "CERA_PROVIDER_BUDGET_EXCEEDED"
    PROVIDER_TRANSPORT_FAILED = "CERA_PROVIDER_TRANSPORT_FAILED"
    PLANNER_RESULT_UNAVAILABLE = "CERA_PLANNER_RESULT_UNAVAILABLE"
    PROMOTION_BLOCKED = "CERA_PROMOTION_BLOCKED"
    DEPLOYMENT_NOT_AUTHORIZED = "CERA_DEPLOYMENT_NOT_AUTHORIZED"
    REASONER_SESSION_INCOMPATIBLE = "CERA_REASONER_SESSION_INCOMPATIBLE"
    REASONER_SESSION_RECONSTRUCTION_REQUIRED = "CERA_REASONER_SESSION_RECONSTRUCTION_REQUIRED"
    REASONER_SESSION_STATE_CONFLICT = "CERA_REASONER_SESSION_STATE_CONFLICT"


class RetryMode(StrEnum):
    MANUAL_AFTER_REVIEW = "manual_after_review"
    RESUBMIT_CORRECTED_RECEIPT = "resubmit_corrected_receipt"
    NOT_APPLICABLE = "not_applicable"


class CeraError(Exception):
    """Base class for deterministic CERA failures."""


class ContractValidationError(CeraError):
    """A typed record does not satisfy its declared schema."""


class IdentityError(CeraError):
    """A typed ID is malformed or has the wrong kind."""


class CanonicalizationError(CeraError):
    """A value cannot be represented by CERA canonical JSON."""


class ConfigurationError(CeraError):
    """Configuration violates the active phase or schema."""


class StateConflictError(CeraError):
    """Optimistic state or branch-head expectations do not match."""


class ProviderToolRequestError(CeraError):
    """A provider-issued tool request violated a closed request-local policy."""


class TransactionError(CeraError):
    """An authority-store transaction could not commit safely."""


class GenesisImportBlockedError(ContractValidationError):
    """A Genesis import stopped before writes at a typed creator-input boundary."""

    def __init__(self, code: ErrorCode, message: str) -> None:
        self.code = code
        super().__init__(message)


class EvidenceServiceError(CeraError):
    """Fail-closed evidence-service error carrying a stable public code."""

    def __init__(self, code: ErrorCode, message: str) -> None:
        self.code = code
        super().__init__(message)
