"""The installed Phase 1 schema registry."""

from __future__ import annotations

from .config import FoundationConfig
from .contracts import (
    AcceptedStoryArtifact,
    BehavioralScenePlan,
    BehavioralTurnControls,
    CreatorRevisionDirective,
    AftermathDecision,
    BlockedTurnCheckpoint,
    CharacterMemoryRecord,
    CommitReceipt,
    ErrorEnvelope,
    EffectiveCharacterProjection,
    EvidenceHit,
    ExternalCompletionReceipt,
    ExternalEventRequest,
    ExternalReceiptValidationReceipt,
    RejectedTurnReceipt,
    SceneDecision,
    SourceClaimLedger,
    TemporaryAftermathProjection,
    TurnRequest,
)
from .schema import SchemaRegistry
from .genesis import (
    CreatorAuthorization,
    GenesisManifest,
    GenesisModule,
    GenesisRecord,
    GenesisRevisionReceipt,
    SyntheticFixtureAuthorization,
)
from .evidence import (
    EvidenceDocument,
    EvidenceLookupReceipt,
    EvidenceObligation,
    EvidenceQueryPlan,
    EvidenceSnapshot,
)
from .kernel import PreparedTurn
from .reasoner import (
    McpEvidenceBridgeReceipt,
    CodexReasonerDraftV2,
    CodexReasonerDraftV3,
    CodexReasonerDraftV4,
    CodexReasonerDraftV5,
    ReasonerOutcome,
    ReasonerOutcomeV3,
    ReasonerOutcomeV4,
    ReasonerOutcomeV5,
    SeedDossierReceipt,
    SceneReasonerReceipt,
    SceneReasonerRequest,
)
from .composer import (
    ComposerCandidate,
    ComposerContextAssemblyReceipt,
    ComposerValidationReceipt,
    DeepSeekCompositionDraftV2,
    DeepSeekCompositionDraftV3,
    DeepSeekCompositionDraftV4,
    DeepSeekCompositionDraftV5,
    DeepSeekCompositionDraftV6,
    RealizationManifest,
    RenderedStory,
    SceneComposerReceipt,
    SceneComposerRequest,
)
from .adult import (
    AdultAuthorityDecision,
    AdultCausalLedger,
    AdultDualRepresentationReceipt,
    AdultMechanicsProposal,
    AdultMechanicsReceipt,
    AdultMechanicsRequest,
    AdultRouteContext,
)
from .adult_craft import (
    AdultCraftCatalogManifest,
    AdultCraftFragment,
    AdultCraftNeed,
    AdultCraftNeedV2,
    AdultCraftNeedV3,
    AdultCraftSelectionReceipt,
    BeatScopedRepairReceipt,
    BeatScopedRepairRequest,
    SpecificityContract,
    SpecificityValidationReceipt,
    SemanticSpecificityRequest,
    SemanticSpecificityResult,
    SemanticSpecificityReceipt,
)
from .resumption.models import AftermathReasonerReceipt
from .consolidation.models import (
    ConsolidationBundle,
    ConsolidationCommitReceipt,
    ConsolidationProposal,
    ConsolidationReasonerReceipt,
    ConsolidationValidationReceipt,
    DerivedConsolidationRequest,
    DerivedView,
    DerivedViewBuildReceipt,
)
from .evaluation import (
    DeploymentReadinessReport,
    EvaluationCase,
    EvaluationRunReport,
    EvaluationSuiteManifest,
    HumanReviewBallot,
    HumanReviewPacket,
    PromotionAssessment,
    PromotionPolicy,
    TelemetryEvent,
)
from .providers import (
    LiveProviderCallReceipt,
    LiveProviderRoute,
    ProviderFailureCallReceipt,
)
from .runtime import (
    LiveShapedTurnReceipt,
    FinalStoryAcceptanceReceipt,
    IngressPublicationEvidence,
    OrdinaryApplicationReceipt,
    OrdinaryApplicationRequest,
    OrdinaryApplicationRequestV2,
    PostPublicationOperationReceipt,
    PostPublicationStatusReport,
    PostPublicationWorkErrorEnvelope,
    PostPublicationWorkSummary,
    TurnFailureEvidenceBundle,
    TurnFailureEvidenceBundleV2,
    TurnFailureEvidenceBundleV3,
    TurnStageAuditEntry,
)
from .ingress import (
    IntentInterpretationDraft,
    IntentInterpretationReceipt,
    RawTurnEnvelope,
)
from .realization import (
    SceneRealizationVerificationReceipt,
    SceneRealizationVerificationRequest,
)
from .source_inventory import RepositorySourceInventoryReceipt
from .prompting import (
    PromptCompilationReceipt,
    PromptModuleRegistryManifest,
    PromptSelectionRequest,
)
from .creator_review import (
    CreatorAcceptTimingReceipt,
    CreatorCorrectionDiagnostic,
    CreatorReviewAssessment,
    CreatorReviewRecord,
    PreparedPublicationPackage,
)
from .continuous import (
    AcceptedFinalSequenceEnvelopeV1,
    CharacterSummaryEnvelopeV1,
    FinalSequenceV1,
    RichPlannerSequenceV1,
    SceneSummaryV1,
    ValidatorFinalizationPackageV1,
)
from .continuous.sessions import (
    ContinuousSessionCompatibilityV1,
    ContinuousSessionHandleV1,
    ContinuousSessionSnapshotV1,
)
from .continuous.world import WorldPromotionReceiptV1
from .continuous.provider import (
    ContinuousDeepSeekDraftV1,
    ContinuousValidatorDraftV1,
)


def build_schema_registry() -> SchemaRegistry:
    registry = SchemaRegistry()
    for model in (
        FoundationConfig,
        ErrorEnvelope,
        TurnRequest,
        EvidenceHit,
        SceneDecision,
        AcceptedStoryArtifact,
        BehavioralTurnControls,
        CreatorRevisionDirective,
        SourceClaimLedger,
        BehavioralScenePlan,
        EffectiveCharacterProjection,
        BlockedTurnCheckpoint,
        RejectedTurnReceipt,
        TemporaryAftermathProjection,
        ExternalEventRequest,
        ExternalCompletionReceipt,
        ExternalReceiptValidationReceipt,
        AftermathDecision,
        CharacterMemoryRecord,
        CommitReceipt,
        GenesisManifest,
        GenesisModule,
        GenesisRecord,
        CreatorAuthorization,
        GenesisRevisionReceipt,
        SyntheticFixtureAuthorization,
        EvidenceSnapshot,
        EvidenceDocument,
        EvidenceLookupReceipt,
        EvidenceQueryPlan,
        EvidenceObligation,
        PreparedTurn,
        RawTurnEnvelope,
        IntentInterpretationDraft,
        IntentInterpretationReceipt,
        SceneReasonerRequest,
        CodexReasonerDraftV2,
        CodexReasonerDraftV3,
        CodexReasonerDraftV4,
        CodexReasonerDraftV5,
        ReasonerOutcomeV3,
        ReasonerOutcomeV4,
        ReasonerOutcomeV5,
        ReasonerOutcome,
        SeedDossierReceipt,
        SceneReasonerReceipt,
        McpEvidenceBridgeReceipt,
        SceneComposerRequest,
        ComposerContextAssemblyReceipt,
        DeepSeekCompositionDraftV2,
        DeepSeekCompositionDraftV3,
        DeepSeekCompositionDraftV4,
        DeepSeekCompositionDraftV5,
        DeepSeekCompositionDraftV6,
        ComposerCandidate,
        RealizationManifest,
        SceneComposerReceipt,
        ComposerValidationReceipt,
        FinalStoryAcceptanceReceipt,
        SceneRealizationVerificationRequest,
        SceneRealizationVerificationReceipt,
        RenderedStory,
        AdultAuthorityDecision,
        AdultCausalLedger,
        AdultRouteContext,
        AdultDualRepresentationReceipt,
        AdultMechanicsRequest,
        AdultMechanicsProposal,
        AdultMechanicsReceipt,
        AdultCraftFragment,
        AdultCraftCatalogManifest,
        AdultCraftNeed,
        AdultCraftNeedV2,
        AdultCraftNeedV3,
        AdultCraftSelectionReceipt,
        SpecificityContract,
        SpecificityValidationReceipt,
        SemanticSpecificityRequest,
        SemanticSpecificityResult,
        SemanticSpecificityReceipt,
        BeatScopedRepairRequest,
        BeatScopedRepairReceipt,
        AftermathReasonerReceipt,
        DerivedConsolidationRequest,
        ConsolidationProposal,
        ConsolidationReasonerReceipt,
        ConsolidationValidationReceipt,
        ConsolidationBundle,
        ConsolidationCommitReceipt,
        DerivedView,
        DerivedViewBuildReceipt,
        EvaluationCase,
        EvaluationSuiteManifest,
        EvaluationRunReport,
        TelemetryEvent,
        HumanReviewPacket,
        HumanReviewBallot,
        PromotionPolicy,
        PromotionAssessment,
        DeploymentReadinessReport,
        LiveProviderRoute,
        LiveProviderCallReceipt,
        ProviderFailureCallReceipt,
        LiveShapedTurnReceipt,
        IngressPublicationEvidence,
        TurnFailureEvidenceBundle,
        TurnFailureEvidenceBundleV2,
        TurnFailureEvidenceBundleV3,
        TurnStageAuditEntry,
        OrdinaryApplicationRequest,
        OrdinaryApplicationRequestV2,
        OrdinaryApplicationReceipt,
        PostPublicationWorkSummary,
        PostPublicationWorkErrorEnvelope,
        PostPublicationStatusReport,
        PostPublicationOperationReceipt,
        RepositorySourceInventoryReceipt,
        PromptModuleRegistryManifest,
        PromptSelectionRequest,
        PromptCompilationReceipt,
        CreatorReviewAssessment,
        CreatorAcceptTimingReceipt,
        CreatorCorrectionDiagnostic,
        PreparedPublicationPackage,
        CreatorReviewRecord,
        RichPlannerSequenceV1,
        CharacterSummaryEnvelopeV1,
        AcceptedFinalSequenceEnvelopeV1,
        FinalSequenceV1,
        SceneSummaryV1,
        ValidatorFinalizationPackageV1,
        ContinuousSessionCompatibilityV1,
        ContinuousSessionHandleV1,
        ContinuousSessionSnapshotV1,
        WorldPromotionReceiptV1,
        ContinuousValidatorDraftV1,
        ContinuousDeepSeekDraftV1,
    ):
        registry.register(model)
    return registry
